language: node_js
node_js:
  - "8"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - npm install -g yarn --cache-min 999999999
install:
  - yarn
cache:
  directories:
  - node_modules
before_script:
  - "npm i -g gatsby"
  - "npm i -g gatsby-cli"
  - "gatsby new blog https://github.com/brute4s99/pydata.git"
  - "cd blog"
script:
  - "npm run test"
after_success:
  - "npm run build"
deploy:
  skip-cleanup: true
  provider: pages
  github-token: $GITHUB_TOKEN
  local_dir: blog/public
  keep-history: true
  on:
    branch: master
